import Head from "next/head";
import { useMoralis } from "react-moralis";
import Login from "../components/Login";
import Header from "../components/Header";
import Messages from "../components/Messages";

function Home() {
  const { isAuthenticated } = useMoralis();

  if (!isAuthenticated) return <Login />;

  return (
    <div className="h-screen overflow-y-scroll overflow-hidden bg-zinc-900 scrollbar-hide">
      <Head>
        <title>Whysper</title>
        <meta name="Please Whysper" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💬</text></svg>"
        />
      </Head>

      <div>
        <Header />
        <Messages />
      </div>
    </div>
  );
}

export default Home;
