import Head from "next/head";
import { useMoralis } from "react-moralis";
import { useState } from "react";
import Login from "../components/Login";
import Image from "next/image";

function Home() {
  const { isAuthenticated, logout } = useMoralis();
  const [nameInput, setNameInput] = useState("");

  if (!isAuthenticated)
    return <Login nameInput={nameInput} setNameInput={setNameInput} />;

  return (
    <div>
      <Head>
        <title>Metachat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-neutral-600/60 flex flex-col absolute h-screen z-50 items-center justify-center w-full gap-y-5 md:gap-y-10">
        <h1 className="text-4xl text-center md:text-5xl xl:text-6xl text-white font-thin m-w-">
          Hey {nameInput}! <br /> Welcome to Metaverse Chat
        </h1>
        <button
          className="bg-yellow-500 font-semibold px-4 py-2 md:px-5 md:py-3 rounded-full text-white"
          onClick={logout}
        >
          Disconnect
        </button>
      </div>

      <div className="h-screen w-full">
        <Image
          src="/images/login-bg-image.jpg"
          className="object-cover "
          layout="fill"
          alt="login-image"
        />
      </div>
    </div>
  );
}

export default Home;
